package auxiliary;

import javax.jws.WebMethod;
import javax.jws.WebParam;
import javax.jws.WebResult;
import javax.jws.WebService;
import javax.xml.bind.annotation.XmlSeeAlso;
import javax.xml.ws.RequestWrapper;
import javax.xml.ws.ResponseWrapper;

/**
 * This class was generated by the JAX-WS RI. JAX-WS RI 2.2.6-1b01 Generated
 * source version: 2.2
 *
 */
@WebService(name = "Mutalyzer", targetNamespace = "http://mutalyzer.nl/2.0/services")
@XmlSeeAlso({
    ObjectFactory.class
})
public interface Mutalyzer {

    /**
     *
     * Converts I{c.} to I{g.} notation or vice versa
     *
     * @arg build: The genome build (hg19, hg18, mm10).
     * @type build: string
     * @arg variant: The variant in either I{c.} or I{g.} notation, full HGVS
     * notation, including NM_, NC_, or LRG_ accession number.
     * @type variant: string
     * @kwarg gene: Optional gene name. If given, return variant descriptions on
     * all transcripts for this gene.
     * @type gene: string
     *
     * @return: The variant(s) in either I{g.} or I{c.} notation.
     * @rtype: list
     *
     *
     * @param build
     * @param gene
     * @param variant
     * @return returns test.StringArray
     */
    @WebMethod(action = "numberConversion")
    @WebResult(name = "numberConversionResult", targetNamespace = "http://mutalyzer.nl/2.0/services")
    @RequestWrapper(localName = "numberConversion", targetNamespace = "http://mutalyzer.nl/2.0/services", className = "auxiliary.NumberConversion")
    @ResponseWrapper(localName = "numberConversionResponse", targetNamespace = "http://mutalyzer.nl/2.0/services", className = "auxiliary.NumberConversionResponse")
    public StringArray numberConversion(
            @WebParam(name = "build", targetNamespace = "http://mutalyzer.nl/2.0/services") String build,
            @WebParam(name = "variant", targetNamespace = "http://mutalyzer.nl/2.0/services") String variant,
            @WebParam(name = "gene", targetNamespace = "http://mutalyzer.nl/2.0/services") String gene);

}
